version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: smart-helpdesk-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: smart-helpdesk
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - helpdesk-network

  redis:
    image: redis:7-alpine
    container_name: smart-helpdesk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - helpdesk-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: smart-helpdesk-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/smart-helpdesk?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server/logs:/app/logs
      - ./server/uploads:/app/uploads
    networks:
      - helpdesk-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: smart-helpdesk-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - helpdesk-network

volumes:
  mongodb_data:
  redis_data:

networks:
  helpdesk-network:
    driver: bridge
